"""for bypass tests

Revision ID: 8de45342dab6
Revises: 3e1847aa60d9
Create Date: 2024-02-16 23:23:26.713042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de45342dab6'
down_revision = '3e1847aa60d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
