"""for bypass tests

Revision ID: e6c3d4e4bbb6
Revises: 6a96bfb87bd7
Create Date: 2024-02-16 08:25:50.469873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6c3d4e4bbb6'
down_revision = '6a96bfb87bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
